version: "3.9"

services:

  sts:
    build:
      context: ./sts
      dockerfile: Dockerfile
    expose:
      - 3001
    networks:
      - isc
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:3001/health/alive || exit 1"
      interval: 20s
      timeout: 10s
      retries: 3
      
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - 24950
    networks:
      - isc

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "34567:3000"
    depends_on:
      sts:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/health/alive || exit 1
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 5s
    networks:
      - isc

networks:
  isc: