version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - 24950
    networks:
      - isc

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "34567:3000"
    depends_on:
      - server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health/alive"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 5s
    command: ["/bin/sh", "-c", "sleep 10 && npm start"]
    networks:
      - isc

networks:
  isc: