version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "34567:3000"
      - "24950:24950"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health/alive"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 5s

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    command: ["/bin/sh", "-c", "sleep 10 && npm start"]
